# Generated by Django 4.0.3 on 2022-04-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_todo_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
