# Generated by Django 4.0.3 on 2022-04-20 05:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todolist_title_alter_todolistitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=240, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='title',
            field=models.CharField(max_length=240, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='todo_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo.todolist'),
        ),
    ]
