# Generated by Django 4.0.3 on 2022-04-20 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todolist_created_todolistitem_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='todo_list',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo.todolist'),
        ),
    ]
