# Generated by Django 4.0.3 on 2022-04-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_alter_todolistitem_todo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='todo_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo.todolist'),
        ),
    ]
